In [36]:
import numpy as np
import scipy
from sympy import Matrix

In [3]:
A = np.array(
    [
        [8, -3, 0, -7, 2],
        [-9, 4, 5, 11, -7],
        [6, -2, 2, -4, 4],
        [5, -1, 7, 0, 10],
    ]
)

print(A)

[[ 8 -3  0 -7  2]
 [-9  4  5 11 -7]
 [ 6 -2  2 -4  4]
 [ 5 -1  7  0 10]]


In [45]:
columns = [
    0,
    1,
#     2,
#     3,
    4,
]

B = A[:, columns]

Matrix(B).rref(pivots=False)

np.linalg.lstsq(B, np.zeros(4), rcond=-1)[0]

array([0., 0., 0.])

In [47]:
columns = [
    0,
    1,
#     2,
#     3,
    4,
]

B = A[:, columns]
v = A[:, 3]

B = A[:, [0, 1, 4, 2]]

Matrix(B).rref(pivots=False)

Matrix([
[1, 0, 0, 3],
[0, 1, 0, 8],
[0, 0, 1, 0],
[0, 0, 0, 0]])