In [6]:
import numpy as np
import sympy as sym

**37**

In [3]:
A = np.array(
    [
        [7, 2, -5, 8],
        [-5, -3, 4, -9],
        [6, 10, -2, 7],
        [-7, 9, 2, 15]
    ]
)

print(A)

[[ 7  2 -5  8]
 [-5 -3  4 -9]
 [ 6 10 -2  7]
 [-7  9  2 15]]


In [9]:
A = sym.Matrix(A)

In [11]:
A.rref(pivots=False)

Matrix([
[1, 0, 0,  -93/50],
[0, 1, 0,   53/50],
[0, 0, 1, -189/50],
[0, 0, 0,       0]])

**39**

In [21]:
A = [
        [12, -7, 11, -9, 5],
        [-9, 4, -8, 7, -3],
        [-6, 11, -7, 3, -9],
        [4, -6, 10, -5, 12]
]

A = sym.Matrix(A)

A.rref(pivots=False)

Matrix([
[1, 0, 0, -10/21, 0],
[0, 1, 0, -25/84, 0],
[0, 0, 1, -41/84, 0],
[0, 0, 0,      0, 1]])

In [22]:
cols = [
    0,
    1,
    2,
#     3,
    4
]


A[:, cols].rref(pivots=False)

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]])