In [1]:
import numpy as np

33.

In [20]:
n = 4

A = np.random.uniform(low=-10, high=10, size=(n, n))

det_A = np.linalg.det(A)

A

array([[ 0.31620358, -1.12290749,  0.82795268,  5.17673193],
       [-7.83111011,  7.54857101, -3.70449463, -4.31418072],
       [ 1.16018416,  2.44076131,  5.10269167, -4.2306648 ],
       [-8.07183032,  2.06733846,  0.93771061,  2.63697173]])

In [21]:
C = np.zeros((4, 4))

for i in range(n):
    for j in range(n):
        A_ij = np.delete(A, i, axis=0)
        A_ij = np.delete(A_ij, j, axis=1)
        C[i, j] = ((-1)**((i+1)+(j+1)))*np.linalg.det(A_ij)
        
        
A_inv = (1/det_A)*(C.transpose())

A_inv

array([[ 1.66566196e-01,  5.58427667e-02,  4.38790405e-02,
        -1.65233188e-01],
       [ 3.23592154e-01,  1.86477462e-01,  1.10863842e-01,
        -1.52305241e-01],
       [ 1.52443367e-02, -6.28509698e-02,  1.33043012e-01,
         8.06963908e-02],
       [ 2.50751565e-01,  4.70908842e-02,  8.92087656e-05,
        -3.58508351e-02]])

In [23]:
print(A_inv - np.linalg.inv(A))

[[ 5.55111512e-17 -6.93889390e-18 -6.93889390e-18  5.55111512e-17]
 [ 2.22044605e-16  1.11022302e-16  1.38777878e-17 -1.11022302e-16]
 [ 5.20417043e-18 -1.38777878e-17  8.32667268e-17  2.77555756e-17]
 [ 0.00000000e+00  2.08166817e-17  1.35525272e-20  0.00000000e+00]]


34.

In [34]:
n = 4

A = np.random.uniform(low=-10, high=10, size=(n, n))
det_A = np.linalg.det(A)

b = np.random.uniform(low=-10, high=10, size=(n))

print(A)
print()
print(b)

[[-2.31119587 -3.15436211  4.14799476 -8.0840155 ]
 [ 3.18672078  6.28317151  8.14575437 -9.81786601]
 [ 0.54451361  2.85742212 -1.58999426 -7.34661316]
 [ 3.807517   -8.76463797 -8.53691595 -3.94555605]]

[ 5.2567126  -5.91814445  5.94907461  6.60073124]


In [36]:
def cramer_i(i):
    A_i = A.copy()
    A_i[:, i] = b
    det_Ai = np.linalg.det(A_i)
    x_i = det_Ai / det_A
    return x_i

x = np.zeros(n)

for i in range(n):
    x[i] = cramer_i(i)
    
x

array([-1.41532955, -0.07212963, -0.99412415, -0.72757253])

In [37]:
x - np.linalg.inv(A) @ b

array([3.10862447e-15, 1.80411242e-16, 2.22044605e-16, 8.88178420e-16])