In [1]:
import numpy as np

In [9]:
A = np.random.randint(3, size=(4, 4))

A

array([[2, 1, 2, 1],
       [2, 1, 2, 1],
       [0, 0, 2, 1],
       [0, 1, 1, 0]])

In [10]:
A_T = A.transpose()

A_T

array([[2, 2, 0, 0],
       [1, 1, 0, 1],
       [2, 2, 2, 1],
       [1, 1, 1, 0]])

In [11]:
np.linalg.eigvals(A)

array([ 3.69962815e+00, -4.60504870e-01, -7.01251052e-17,  1.76087672e+00])

In [13]:
np.linalg.eigvals(A_T)

array([ 3.69962815e+00,  1.76087672e+00,  1.45972935e-16, -4.60504870e-01])

In [12]:
np.linalg.eig(A)

EigResult(eigenvalues=array([ 3.69962815e+00, -4.60504870e-01, -7.01251052e-17,  1.76087672e+00]), eigenvectors=array([[ 0.68373485,  0.04997892,  0.2       ,  0.62950328],
       [ 0.68373485,  0.04997892, -0.4       ,  0.62950328],
       [ 0.12929952,  0.37557108,  0.4       , -0.44297943],
       [ 0.21976111, -0.92409446, -0.8       ,  0.10592669]]))