In [7]:
import numpy as np
import scipy

In [ ]:
   A = [-6 4 0 9;-3 0 1 6;-1 -2 1 0;-4 4 0 7]
elseif ex==34
   A = [0 13 8 4;4 9 8 4;8 6 12 8;0 5 0 -4]
elseif ex==35
   A = [11 -6 4 -10 -4;-3 5 -2 4 1;-8 12 -3 12 4;1 6 -2 3 -1;
8 -18 8 -14 -1]
elseif ex==36
   A = [4 4 2 3 -2;0 1 -2 -2 2;6 12 11 2 -4;9 20 10 10 -6;15 28 14 5 -3]

In [2]:
A = np.array(
    [
        [-6, 4, 0, 9],
        [-3, 0, 1, 6],
        [-1, -2, 1, 0],
        [-4, 4, 0, 7]
    ]
)

In [4]:
eigenvalues, eigenvectors = np.linalg.eig(A)

eigenvalues, eigenvectors

(array([ 5., -2.,  1., -2.]),
 array([[-0.63245553,  0.79971478, -0.26261287,  0.49476378],
        [-0.31622777,  0.30334009,  0.13130643, -0.65085374],
        [ 0.31622777,  0.46879832,  0.91914503, -0.26898123],
        [-0.63245553,  0.22061097, -0.26261287,  0.50916334]]))

In [9]:
for eigenvalue in eigenvalues:

    B = A - eigenvalue * np.identity(4)
    basis = scipy.linalg.null_space(B)
    
    print(basis)

[[-0.63245553]
 [-0.31622777]
 [ 0.31622777]
 [-0.63245553]]
[[-0.8057784  -0.33924767]
 [ 0.31493544 -0.71415059]
 [-0.05863584 -0.58918295]
 [-0.49809504  0.16662352]]
[[-0.26261287]
 [ 0.13130643]
 [ 0.91914503]
 [-0.26261287]]
[[ 0.86132153  0.14997678]
 [ 0.12091972 -0.77108613]
 [ 0.36772033 -0.46406516]
 [ 0.32906747  0.40936129]]


In [15]:
B = A - 5 * np.identity(4)
basis = scipy.linalg.null_space(B)

(basis * 6.3245553 * 0.5).round(0)

array([[ 2.],
       [ 1.],
       [-1.],
       [ 2.]])

In [16]:
B = A + 2 * np.identity(4)
basis = scipy.linalg.null_space(B)

# (basis * 6.3245553 * 0.5).round(0)
basis

array([[ 0.86132153,  0.14997678],
       [ 0.12091972, -0.77108613],
       [ 0.36772033, -0.46406516],
       [ 0.32906747,  0.40936129]])