In [1]:
import numpy as np

# 32.

In [2]:
A = np.array(
    [
        [0.5, 0.5, 0.5, 0.5],
        [0.5, 0.5, -0.5, -0.5],
        [0.5, -0.5, 0.5, -0.5],
        [0.5, -0.5, -0.5, 0.5],
    ]
)

A

array([[ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5, -0.5, -0.5],
       [ 0.5, -0.5,  0.5, -0.5],
       [ 0.5, -0.5, -0.5,  0.5]])

In [3]:
a_1 = A[0]
a_2 = A[1]
a_3 = A[2]
a_4 = A[3]

a_1

array([0.5, 0.5, 0.5, 0.5])

In [4]:
for a in A:
    print(np.linalg.norm(a))

1.0
1.0
1.0
1.0


In [5]:
for i, a_i in enumerate(A):
    for j, a_j in enumerate(A):
        print(i+1, j+1, np.dot(a_i, a_j))

1 1 1.0
1 2 0.0
1 3 0.0
1 4 0.0
2 1 0.0
2 2 1.0
2 3 0.0
2 4 0.0
3 1 0.0
3 2 0.0
3 3 1.0
3 4 0.0
4 1 0.0
4 2 0.0
4 3 0.0
4 4 1.0


In [6]:
u = 10 * np.random.rand(4)
v = 10 * np.random.rand(4)

u, v

(array([3.61349574, 6.8598916 , 7.77900785, 1.72721543]),
 array([0.62499126, 8.51543631, 2.30741292, 8.95415029]))

In [7]:
u_norm = np.linalg.norm(u)
Au_norm = np.linalg.norm(A @ u)

print(u_norm)
print(Au_norm)

11.118079892844218
11.118079892844218


In [8]:
v_norm = np.linalg.norm(v)
Av_norm = np.linalg.norm(A @ v)

print(v_norm)
print(Av_norm)

12.585874279888415
12.585874279888413


In [9]:
(u @ v)/(u_norm * v_norm)

0.6723933023508817

In [10]:
((A @ u) @ (A @ v))/(Au_norm * Av_norm)

0.6723933023508818

# 33.

In [11]:
x = np.random.randint(5, size=(4,))
y = np.random.randint(5, size=(4,))
v = np.random.randint(5, size=(4,))

x, y, v

(array([1, 1, 0, 3]), array([1, 1, 3, 2]), array([1, 4, 1, 1]))

In [12]:
((x @ v) / (v @ v)) * v

array([0.42105263, 1.68421053, 0.42105263, 0.42105263])

In [13]:
((y @ v) / (v @ v)) * v

array([0.52631579, 2.10526316, 0.52631579, 0.52631579])

In [14]:
(((x + y) @ v) / (v @ v)) * v

array([0.94736842, 3.78947368, 0.94736842, 0.94736842])

In [15]:
(((10 * x) @ v) / (v @ v)) * v

array([ 4.21052632, 16.84210526,  4.21052632,  4.21052632])

# 34.

In [16]:
A = np.array(
    [
        [-6, 3, -27, -33, -13],
        [6, -5, 25, 28, 14],
        [8, -6, 34, 38, 18],
        [12, -10, 50, 41, 23],
        [14, -21, 49, 29, 33]
    ]
)