In [3]:
import numpy as np

In [7]:



def compute_distribution(T_left, T_right, T_lower, T_upper):
    A = np.array(
        [
            [4, -1, 0, -1],
            [-1, 4, -1, 0],
            [-1, 0, -1, 4],
            [0, -1, 4, -1],
        ]
    )
    
    Tb = np.array(
        [
            T_left+T_upper,
            T_upper+T_right,
            T_left+T_lower,
            T_right+T_lower,
        ]
    )


    temp_dist = np.linalg.solve(A, Tb)

    return temp_dist
    





array([20. , 27.5, 30. , 22.5])

In [8]:
T_left = 10
T_right = 40
T_lower = 30
T_upper = 20

compute_distribution(T_left, T_right, T_lower, T_upper)

array([20. , 27.5, 30. , 22.5])

In [11]:
T_left = 0
T_right = 0
T_lower = 20
T_upper = 20

compute_distribution(T_left*3, T_right*3, T_lower*3, T_upper*3)

array([30., 30., 30., 30.])

In [10]:
T_left = 10
T_right = 40
T_lower = 10
T_upper = 0

compute_distribution(T_left, T_right, T_lower, T_upper)

array([10. , 17.5, 20. , 12.5])

In [ ]:
b = np.array([5, 15, 0, 10, 0, 10, 20, 30])

d = np.array([-1, 0, -1, 0, -1, 0, -1])

A = np.zeros(8)
A = A + np.diagflat(d, 1)
A = A + np.diagflat(-np.ones(6), 2)
A = A + A.T + 4 * np.identity(8)

print(A.shape)
print(A)