In [1]:
import numpy as np

35.

In [2]:
np.zeros((5, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [3]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [5]:
np.diag([3, 5, 7, 2, 4])

array([[3, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 7, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 4]])

36.

In [6]:
np.random.rand(6, 4)

array([[0.53123061, 0.66875327, 0.37048547, 0.13643445],
       [0.20038799, 0.80575439, 0.18570934, 0.24054883],
       [0.3371315 , 0.80832734, 0.80202125, 0.44387152],
       [0.62021715, 0.15509003, 0.94571618, 0.90914645],
       [0.0868754 , 0.90312986, 0.32690635, 0.49747074],
       [0.38723134, 0.71315312, 0.84260399, 0.26587988]])

In [7]:
np.random.uniform(-9, 9, size=(3, 3))

array([[ 3.6785619 ,  8.14057939,  0.98561233],
       [ 8.18462131, -3.23586997,  6.82258741],
       [-0.18546809,  6.00631081,  1.26550778]])

37.

In [20]:
A = np.random.rand(4, 4)
B = np.random.rand(4, 4)
A

array([[0.63853152, 0.63722635, 0.44800979, 0.14378612],
       [0.96181393, 0.37513697, 0.31389425, 0.46655248],
       [0.9842798 , 0.14639995, 0.80676732, 0.58740749],
       [0.38617698, 0.24488574, 0.03760329, 0.8151328 ]])

In [10]:
I = np.identity(4)

In [14]:
(A + I) * (A - I) - (A**2 - I) == 0 

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [21]:
(A + B) * (A - B) - (A**2 - B**2) == 0 

array([[ True,  True,  True, False],
       [ True, False,  True,  True],
       [ True,  True, False, False],
       [ True, False,  True, False]])

38.

In [22]:
(A + B).T - (A.T + B.T) == 0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [23]:
(A * B).T - (B.T) * (A.T) == 0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

39.

In [28]:
S = np.array(
    [
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0],
    ]
)

S

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [34]:
S_k = S.copy()
for k in range(2, 7):
    S_k = np.matmul(S_k, S)
    print(S_k)

[[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


40.

In [35]:
A = np.array(
    [
        [1/6, 1/2, 1/3],
        [1/2, 1/4, 1/4],
        [1/3, 1/4, 5/12]
    ]
)

In [36]:
from numpy.linalg import matrix_power

In [38]:
for k in [10, 20, 30]:
    print(matrix_power(A, k))

[[0.33333725 0.33333011 0.33333264]
 [0.33333011 0.33333599 0.3333339 ]
 [0.33333264 0.3333339  0.33333346]]
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
