In [1]:
import numpy as np

41.

In [4]:
D = np.array(
    [
        [.0040, .0030, .0010, .0005],
        [.0030, .0050, .0030, .0010],
        [.0010, .0030, .0050, .0030],
        [.0005, .0010, .0030, .0040]
    ]
)

y = np.array([.08, .12, .16, .12])

print(D)
print(y)

[[0.004  0.003  0.001  0.0005]
 [0.003  0.005  0.003  0.001 ]
 [0.001  0.003  0.005  0.003 ]
 [0.0005 0.001  0.003  0.004 ]]
[0.08 0.12 0.16 0.12]


In [5]:
np.linalg.det(D)

5.999999999999988e-11

In [7]:
np.linalg.inv(D) @ y

array([12. ,  1.5, 21.5, 12. ])

42.

In [8]:
y = np.array([0, .24, 0, 0])

np.linalg.inv(D) @ y

array([-104.,  167., -113.,   56.])

In [10]:
np.linalg.inv(D)

array([[ 533.33333333, -433.33333333,  233.33333333, -133.33333333],
       [-433.33333333,  695.83333333, -470.83333333,  233.33333333],
       [ 233.33333333, -470.83333333,  695.83333333, -433.33333333],
       [-133.33333333,  233.33333333, -433.33333333,  533.33333333]])