In [1]:
import numpy as np

41.

In [2]:
A = np.array(
    [
        [4.5, 3.1],
        [1.6, 1.1]
    ]
)

b = np.array([19.249, 6.843])

np.linalg.solve(A, b)

array([3.94, 0.49])

In [3]:
A = np.array(
    [
        [4.5, 3.1],
        [1.6, 1.1]
    ]
)

b = np.array([19.25, 6.84])

np.linalg.solve(A, b)

array([2.9, 2. ])

In [6]:
round(np.abs(2.9 - 3.94) / 3.94, 2) * 100

26.0

In [7]:
round(np.abs(2 - 0.49) / 0.49, 2) * 100

308.0

In [11]:
np.linalg.cond(A)

3362.9997026460064

42.

In [59]:
A = np.array(
    [
        [4, 0, -7, -7],
        [-6, 1, 11, 9],
        [7, -5, 10, 19],
        [-1, 2, 3, -1]
    ]
)

print(A)

[[ 4  0 -7 -7]
 [-6  1 11  9]
 [ 7 -5 10 19]
 [-1  2  3 -1]]


In [60]:
np.linalg.cond(A)

23682.927874659617

In [61]:
x = (np.random.rand(4)*10)

b = A @ x

In [62]:
b.dtype

dtype('float64')

In [63]:
x_1 = np.linalg.solve(A, b)
x_1 - x

array([-3.55271368e-14, -1.04805054e-12,  5.09814413e-13, -5.30242517e-13])

###### 

In [66]:
x

array([7.20875103724565 , 3.958220451780279, 5.994076306988045,
       5.790386914078062])

In [37]:
A.dtype

dtype('int16')

In [71]:
np.set_printoptions(precision=5)

44.

In [76]:
from scipy.linalg import hilbert

H = hilbert(5)

print(H)

[[1.      0.5     0.33333 0.25    0.2    ]
 [0.5     0.33333 0.25    0.2     0.16667]
 [0.33333 0.25    0.2     0.16667 0.14286]
 [0.25    0.2     0.16667 0.14286 0.125  ]
 [0.2     0.16667 0.14286 0.125   0.11111]]


In [77]:
np.linalg.cond(H)

476607.2502419222

In [79]:
e_5 = np.array([0, 0, 0, 0, 1])

np.linalg.solve(H, e_5) - np.array([630,-12600,56700,-88200,44100])

array([-4.30191e-10,  6.60475e-09, -2.43890e-08,  3.25090e-08,
       -1.43409e-08])

In [85]:
H = hilbert(16)

H_inv = np.linalg.inv(H)

In [86]:
np.set_printoptions(precision=3)

print(H @ H_inv)

[[ 1.000e+00  2.861e-06 -1.984e-04 -1.221e-03 -1.367e-02  1.406e-01
   6.250e-02 -2.500e-01  0.000e+00 -5.000e-01 -6.250e-02  1.016e-01
   5.625e-01  1.250e-01 -1.250e-01 -3.125e-02]
 [ 1.909e-08  1.000e+00  5.969e-06 -2.622e-03  7.170e-03 -6.519e-02
   3.350e-01 -4.637e-01  9.326e-01 -4.216e-01  5.131e-02  2.323e-02
   7.310e-01 -9.938e-01  5.541e-02 -1.978e-01]
 [-3.646e-09  9.654e-07  1.000e+00 -1.090e-03 -7.637e-03 -4.056e-02
   1.300e-01  1.232e-01  4.400e-01  5.297e-02 -7.787e-02  1.893e-01
   5.309e-02 -1.084e-01 -8.579e-02 -1.250e-01]
 [-1.894e-08  5.507e-06 -1.160e-04  9.999e-01 -1.094e-02  3.476e-02
  -2.058e-01  4.589e-01  2.524e-01  3.857e-01 -2.230e-01  8.313e-02
  -4.875e-01  7.756e-01 -4.004e-01 -5.549e-02]
 [-1.088e-08  2.898e-06 -6.912e-05 -8.016e-04  9.877e-01  9.162e-03
   1.487e-01  3.016e-01 -2.585e-01  1.336e-01 -5.414e-02  1.804e-01
  -4.153e-02  5.538e-01 -3.197e-01 -2.424e-02]
 [ 1.683e-08 -1.318e-06  9.490e-05 -3.166e-03  2.470e-02  8.347e-01
   6.337e-01 -1.2