In [24]:
import numpy as np
from scipy.linalg import lu

31.

In [32]:
b = np.array([5, 15, 0, 10, 0, 10, 20, 30])

d = np.array([-1, 0, -1, 0, -1, 0, -1])

A = np.zeros(8)
A = A + np.diagflat(d, 1)
A = A + np.diagflat(-np.ones(6), 2)
A = A + A.T + 4 * np.identity(8)

print(A.shape)
print(A)

(8, 8)
[[ 4. -1. -1.  0.  0.  0.  0.  0.]
 [-1.  4.  0. -1.  0.  0.  0.  0.]
 [-1.  0.  4. -1. -1.  0.  0.  0.]
 [ 0. -1. -1.  4.  0. -1.  0.  0.]
 [ 0.  0. -1.  0.  4. -1. -1.  0.]
 [ 0.  0.  0. -1. -1.  4.  0. -1.]
 [ 0.  0.  0.  0. -1.  0.  4. -1.]
 [ 0.  0.  0.  0.  0. -1. -1.  4.]]


In [26]:
P, L, U = lu(A)

In [30]:
print(P)
print(L.round(2))
print(U.round(2))

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
[[ 1.    0.    0.    0.    0.    0.    0.    0.  ]
 [-0.25  1.    0.    0.    0.    0.    0.    0.  ]
 [-0.25 -0.07  1.    0.    0.    0.    0.    0.  ]
 [ 0.   -0.27 -0.29  1.    0.    0.    0.    0.  ]
 [ 0.    0.   -0.27 -0.08  1.    0.    0.    0.  ]
 [ 0.    0.    0.   -0.29 -0.29  1.    0.    0.  ]
 [ 0.    0.    0.    0.   -0.27 -0.09  1.    0.  ]
 [ 0.    0.    0.    0.    0.   -0.29 -0.29  1.  ]]
[[ 4.   -1.   -1.    0.    0.    0.    0.    0.  ]
 [ 0.    3.75 -0.25 -1.    0.    0.    0.    0.  ]
 [ 0.    0.    3.73 -1.07 -1.    0.    0.    0.  ]
 [ 0.    0.    0.    3.43 -0.29 -1.    0.    0.  ]
 [ 0.    0.    0.    0.    3.71 -1.08 -1.    0.  ]
 [ 0.    0.    0.    0.    0.    3.39 -0.29 -1.  ]
 [ 0.    0.    0.    0.    0.    0.    3.71 -1.09]
 [ 0.    0.    0.

In [31]:
L @ U - A

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 3.46944695e-18, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.64338815e-17,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 2.33570849e-17, 0.00000000e+00, 0.

In [37]:
y = np.linalg.solve(L, b)
x = np.linalg.solve(U, y)

print(x.round(2))

[ 3.96  6.59  4.24  7.4   5.6   8.76  9.41 12.04]


In [39]:
(A @ x).round(2)

array([ 5., 15., -0., 10., -0., 10., 20., 30.])

In [44]:
A_inv = np.linalg.inv(A)

print(A_inv.round(2))

[[0.3  0.09 0.09 0.05 0.03 0.02 0.01 0.01]
 [0.09 0.3  0.05 0.09 0.02 0.03 0.01 0.01]
 [0.09 0.05 0.33 0.11 0.1  0.06 0.03 0.02]
 [0.05 0.09 0.11 0.33 0.06 0.1  0.02 0.03]
 [0.03 0.02 0.1  0.06 0.33 0.11 0.09 0.05]
 [0.02 0.03 0.06 0.1  0.11 0.33 0.05 0.09]
 [0.01 0.01 0.03 0.02 0.09 0.05 0.3  0.09]
 [0.01 0.01 0.02 0.03 0.05 0.09 0.09 0.3 ]]
