In [15]:
import numpy as np
from scipy.linalg import lu, lu_factor

In [16]:
A = np.array(
    [
        [-5, 3, 4],
        [10, -8, -9],
        [15, 1, 2],
    ]
)

In [19]:
p, l, u = lu(A)

In [20]:
p

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [21]:
l

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.66666667,  1.        ,  0.        ],
       [-0.33333333, -0.38461538,  1.        ]])

In [22]:
u

array([[ 15.        ,   1.        ,   2.        ],
       [  0.        ,  -8.66666667, -10.33333333],
       [  0.        ,   0.        ,   0.69230769]])

In [11]:
np.matmul(p, u)

array([[  0.        ,   0.        ,   0.69230769],
       [  0.        ,  -8.66666667, -10.33333333],
       [ 15.        ,   1.        ,   2.        ]])

In [13]:
lu_factor(A)

(array([[ 15.        ,   1.        ,   2.        ],
        [  0.66666667,  -8.66666667, -10.33333333],
        [ -0.33333333,  -0.38461538,   0.69230769]]),
 array([2, 1, 2], dtype=int32))