In [7]:
import numpy as np
from sympy import Matrix

Practice Problem

In [28]:
I = np.identity(3)

d = np.array([50, 30, 20])

C = np.array(
    [[0.5, 0.4, 0.2],
     [0.2, 0.3, 0.1],
     [0.1, 0.1, 0.3]]
)

print(C)

[[0.5 0.4 0.2]
 [0.2 0.3 0.1]
 [0.1 0.1 0.3]]


In [29]:
x = np.linalg.inv(I - C) @ d
print(x.reshape(-1, 1))

[[225.92592593]
 [118.51851852]
 [ 77.77777778]]


In [30]:
(I - C) @ x

array([50., 30., 20.])

1.

In [3]:
C = np.array(
    [
        [.1, .6, .6],
        [.3, .2, 0],
        [.3, .1, .1],
    ]
)

print(C)

[[0.1 0.6 0.6]
 [0.3 0.2 0. ]
 [0.3 0.1 0.1]]


2.

In [13]:
d = np.array([0, 18, 0]).reshape(-1, 1)

I = np.identity(3)

D = np.concatenate([I - C, d], axis=1)

Matrix(D).rref()[0]

Matrix([
[1, 0, 0, 33.3333333333333],
[0, 1, 0,             35.0],
[0, 0, 1,             15.0]])

3.

In [14]:
d = np.array([18, 0, 0]).reshape(-1, 1)

I = np.identity(3)

D = np.concatenate([I - C, d], axis=1)

Matrix(D).rref()[0]

Matrix([
[1, 0, 0, 40.0],
[0, 1, 0, 15.0],
[0, 0, 1, 15.0]])

4.

In [15]:
d = np.array([18, 18, 0]).reshape(-1, 1)

I = np.identity(3)

D = np.concatenate([I - C, d], axis=1)

Matrix(D).rref()[0]

Matrix([
[1, 0, 0, 73.3333333333333],
[0, 1, 0,             50.0],
[0, 0, 1,             30.0]])

5.

In [16]:
I = np.identity(2)

C = np.array(
    [
        [0., 0.5],
        [0.6, 0.2]
    ]
)

In [27]:
d_0 = np.array([50, 30]).reshape(-1, 1)

P = np.linalg.inv(I - C) 

print(P)

[[1.6 1. ]
 [1.2 2. ]]


In [28]:
P @ d_0

array([[110.],
       [120.]])

In [30]:
d_1 = np.array([1, 0]).reshape(-1, 1)

P @ d_1

array([[1.6],
       [1.2]])

In [31]:
d_t = np.array([51, 30]).reshape(-1, 1)

P @ d_t

array([[111.6],
       [121.2]])

In [33]:
P @ d_0 + P @ d_1

array([[111.6],
       [121.2]])

In [ ]:
   C = [.1588 .0064 .0025 .0304 .0014 .0083 .1594;.0057 .2645 .0436 .0099 .0083 .0201 .3413;.0264 .1506 .3557 .0139 .0142 .0070 .0236;
        .3299 .0565 .0495 .3636 .0204 .0483 .0649;.0089 .0081 .0333 .0295 .3412 .0237 .0020;.1190 .0901 .0996 .1260 .1722 .2368 .3369;
        .0063 .0126 .0196 .0098 .0064 .0132 .0012], 
   d = [74000;56000;10500;25000;17500;196000;5000]
elseif ex==14
   C = [.1588 .0064 .0025 .0304 .0014 .0083 .1594;.0057 .2645 .0436 .0099 .0083 .0201 .3413;.0264 .1506 .3557 .0139 .0142 .0070 .0236;
        .3299 .0565 .0495 .3636 .0204 .0483 .0649;.0089 .0081 .0333 .0295 .3412 .0237 .0020;.1190 .0901 .0996 .1260 .1722 .2368 .3369;
        .0063 .0126 .0196 .0098 .0064 .0132 .0012], 
   d = [99640;75548;14444;33501;23527;263985;6526]

In [38]:
I = np.identity(7)

C = np.array(
    [
        [.1588, .0064, .0025, .0304, .0014, .0083, .1594],
        [.0057, .2645, .0436, .0099, .0083, .0201, .3413],
        [.0264, .1506, .3557, .0139, .0142, .0070, .0236],
        [.3299, .0565, .0495, .3636, .0204, .0483, .0649],
        [.0089, .0081, .0333, .0295, .3412, .0237, .0020],
        [.1190, .0901, .0996, .1260, .1722, .2368, .3369],
        [.0063, .0126, .0196, .0098, .0064, .0132, .0012],
    ]
)

print(C)

[[0.1588 0.0064 0.0025 0.0304 0.0014 0.0083 0.1594]
 [0.0057 0.2645 0.0436 0.0099 0.0083 0.0201 0.3413]
 [0.0264 0.1506 0.3557 0.0139 0.0142 0.007  0.0236]
 [0.3299 0.0565 0.0495 0.3636 0.0204 0.0483 0.0649]
 [0.0089 0.0081 0.0333 0.0295 0.3412 0.0237 0.002 ]
 [0.119  0.0901 0.0996 0.126  0.1722 0.2368 0.3369]
 [0.0063 0.0126 0.0196 0.0098 0.0064 0.0132 0.0012]]


In [37]:
C.shape

(7, 7)

In [39]:
d = np.array([74000, 56000, 10500, 25000, 17500, 196000, 5000]).reshape(-1, 1)

In [42]:
np.linalg.solve(I - C, d).round()

array([[ 99576.],
       [ 97703.],
       [ 51231.],
       [131570.],
       [ 49488.],
       [329554.],
       [ 13835.]])

In [49]:
x_0 = d.copy()

def compute(x_k_prev):
    x_k = d + C @ x_k_prev
    return x_k


x_k_prev = x_0
for k in range(1, 13):
    x_k = compute(x_k_prev)
    print(x_k.flatten().round(2))
    x_k_prev = x_k
    

[ 89344.15  77730.45  26708.05  72334.65  30325.55 265158.2    9327.8 ]
[ 94681.19  87714.51  37577.26 100520.49  38598.01 296563.81  11479.99]
[ 97091.94  92573.11  43867.82 115457.    43490.99 312318.91  12598.76]
[ 98291.61  95033.21  47314.51 123202.51  46247.02 320502.38  13185.46]
[ 98907.24  96305.31  49160.59 127213.72  47756.37 324796.12  13493.84]
[ 99226.61  96969.57  50139.59 129296.74  48569.33 327053.84  13655.95]
[ 99393.06  97317.85  50656.42 130381.63  49002.82 328240.89  13741.13]
[ 99480.03  97500.72  50928.65 130947.97  49232.54 328864.69  13785.87]
[ 99525.54  97596.78  51071.88 131244.12  49353.83 329192.34  13809.37]
[ 99549.38  97647.24  51147.18 131399.15  49417.71 329364.38  13821.71]
[ 99561.88  97673.73  51186.75 131480.38  49451.31 329454.69  13828.18]
[ 99568.43  97687.65  51207.54 131522.96  49468.97 329502.1   13831.58]
