In [1]:
import numpy as np

Practice Problem

In [20]:
d = np.array([50, 30, 20])

C = np.array(
    [[0.5, 0.4, 0.2],
     [0.2, 0.3, 0.1],
     [0.1, 0.1, 0.3]]
)

print(C)

[[0.5 0.4 0.2]
 [0.2 0.3 0.1]
 [0.1 0.1 0.3]]


In [21]:
x = np.linalg.inv(C) @ d
print(x.reshape(-1, 1))

[[33.33333333]
 [66.66666667]
 [33.33333333]]


In [19]:
(np.identity(2) - C) @ (x.reshape(-1, 1))

array([[22.85714286],
       [-1.42857143]])

In [15]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])