In [1]:
import numpy as np

21.

In [2]:
A = np.array(
    [
        [.61, .29, .150],
        [.35, .59, .063],
        [.04, .12, .787],
    ]
)

print(A)

[[0.61  0.29  0.15 ]
 [0.35  0.59  0.063]
 [0.04  0.12  0.787]]


In [3]:
np.linalg.inv(A)

array([[ 2.25855419, -1.03950752, -0.34726068],
       [-1.34953521,  2.34409612,  0.06957081],
       [ 0.09098101, -0.30458861,  1.27768987]])