In [8]:
import numpy as np
import scipy

37.

In [19]:
A = np.array(
    [
        [3, -5, 0, -1, 3],
        [-7, 9, -4, 9, -11],
        [-5, 7, -2, 5, -7],
        [3, -7, -3, 4, 0],
    ]
)

print(A)

[[  3  -5   0  -1   3]
 [ -7   9  -4   9 -11]
 [ -5   7  -2   5  -7]
 [  3  -7  -3   4   0]]


In [25]:
u = scipy.linalg.null_space(A)[:, 0]

u

array([-0.87539355, -0.46223204,  0.07043824, -0.09953224,  0.07182939])

In [16]:
from sympy import Matrix

r = Matrix(A).rref()
U = r[0]
pivot_columns = r[1]

U = np.array(U)

print(U)

[[1 0 5/2 -9/2 7/2]
 [0 1 3/2 -5/2 3/2]
 [0 0 0 0 0]
 [0 0 0 0 0]]
