In [1]:
import numpy as np
from scipy.linalg import null_space

In [2]:
A = np.array(
    [
        [8, -10, -5],
        [2, 17, 2],
        [-9, -18, 4],
    ]
)

In [3]:
sol_3 = np.array([5/9, -2/9, 1])
sol_3

array([ 0.55555556, -0.22222222,  1.        ])

In [4]:
sol_3 * -0.85811633

array([-0.47673129,  0.19069252, -0.85811633])

In [6]:
eigenvalues, eigenvectors = np.linalg.eig(A)

In [9]:
print(eigenvalues)
print(eigenvectors.round(3))

[ 3. 13. 13.]
[[-0.477  0.477 -0.912]
 [ 0.191  0.191  0.35 ]
 [-0.858 -0.858  0.213]]


In [26]:
lambda_ = 13.
I = np.identity(3)

M = A - lambda_ * I

M

array([[ -5., -10.,  -5.],
       [  2.,   4.,   2.],
       [ -9., -18.,  -9.]])

In [34]:
NS = null_space(M)
NS

array([[-0.91287093, -0.        ],
       [ 0.36514837,  0.4472136 ],
       [ 0.18257419, -0.89442719]])

In [38]:
NS * ((0.47673129)/(0.91287093))

array([[-0.47673129, -0.        ],
       [ 0.19069252,  0.23354968],
       [ 0.09534626, -0.46709936]])

In [29]:
v_1 = np.array([-2, 1, 0]).reshape(-1, 1)
v_2 = np.array([-1, 0, 1]).reshape(-1, 1)

basis_0 = np.column_stack([v_1, v_2])

u_1 = eigenvectors[:, 1]
u_2 = eigenvectors[:, 2]

basis = eigenvectors[:, [1, 2]].copy()

print(basis)
print()
print(basis_0)

[[ 0.47673129 -0.9123536 ]
 [ 0.19069252  0.34988759]
 [-0.85811633  0.21257843]]

[[-2 -1]
 [ 1  0]
 [ 0  1]]


In [16]:
from sympy import Matrix

Matrix(basis).rref()[0]

Matrix([
[1, 0],
[0, 1],
[0, 0]])

In [18]:
Matrix(basis_0).rref()[0]

Matrix([
[1, 0],
[0, 1],
[0, 0]])

In [24]:
P_0_1 = np.array(Matrix(np.concatenate([basis_0, basis], axis=1)).rref()[0]).astype(np.float64)
P_0_1

array([[1.        , 0.        , 0.        , 0.30221446],
       [0.        , 1.        , 0.        , 0.42710751],
       [0.        , 0.        , 1.        , 0.25      ]])

In [27]:
P_0_1[:, [2, 3]]

array([[0.        , 0.30221446],
       [0.        , 0.42710751],
       [1.        , 0.25      ]])

In [32]:
np.linalg.solve(basis_0, u_1.reshape(-1, 1))

LinAlgError: Last 2 dimensions of the array must be square

In [37]:
P_0_1 = np.linalg.lstsq(basis_0, basis, rcond=None)[0]
print(P_0_1)

[[ 0.19069252  0.34988759]
 [-0.85811633  0.21257843]]


In [42]:
basis_0 @ P_0_1

array([[ 0.47673129, -0.9123536 ],
       [ 0.19069252,  0.34988759],
       [-0.85811633,  0.21257843]])

In [43]:
basis

array([[ 0.47673129, -0.9123536 ],
       [ 0.19069252,  0.34988759],
       [-0.85811633,  0.21257843]])

In [48]:
U = np.array(
    [
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 0],
    ]
)

V = np.array(
    [
        [1, 1, 0],
        [0, 1, 0],
        [0, 0, 0],
    ]
)


M = np.concatenate([V, U], axis=1)

P = Matrix(M).rref()[0]
P

Matrix([
[1, 0, 0, 1, -1, 0],
[0, 1, 0, 0,  1, 0],
[0, 0, 0, 0,  0, 0]])

In [52]:
P_V_U = np.array(P[:, 3:]).astype(float)
print(P_V_U)

[[ 1. -1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]


In [53]:
x = np.array([0.5, 0.5, 0]).reshape(-1, 1)

P_V_U @ x

array([[0. ],
       [0.5],
       [0. ]])