In [13]:
import numpy as np
from scipy.linalg import null_space

In [2]:
A = np.array(
    [
        [8, -10, -5],
        [2, 17, 2],
        [-9, -18, 4],
    ]
)

In [23]:
sol_3 = np.array([5/9, -2/9, 1])
sol_3

array([ 0.55555556, -0.22222222,  1.        ])

In [24]:
sol_3 * -0.85811633

array([-0.47673129,  0.19069252, -0.85811633])

In [12]:
np.linalg.eig(A)

(array([ 3., 13., 13.]),
 array([[-0.47673129,  0.47673129, -0.09099136],
        [ 0.19069252,  0.19069252,  0.48138299],
        [-0.85811633, -0.85811633, -0.87177462]]))

In [26]:
lambda_ = 13.
I = np.identity(3)

M = A - lambda_ * I

M

array([[ -5., -10.,  -5.],
       [  2.,   4.,   2.],
       [ -9., -18.,  -9.]])

In [34]:
NS = null_space(M)
NS

array([[-0.91287093, -0.        ],
       [ 0.36514837,  0.4472136 ],
       [ 0.18257419, -0.89442719]])

In [38]:
NS * ((0.47673129)/(0.91287093))

array([[-0.47673129, -0.        ],
       [ 0.19069252,  0.23354968],
       [ 0.09534626, -0.46709936]])

In [30]:
NS[:, 0] * 

array([-0.91287093,  0.36514837,  0.18257419])