In [2]:
import numpy as np
import scipy
from sympy import Matrix

**Example 3**

In [2]:
A = np.array(
    [
        [1, 3, 3],
        [-3, -5, -3],
        [3, 3, 1],
    ]
)

print(A)

[[ 1  3  3]
 [-3 -5 -3]
 [ 3  3  1]]


In [7]:
v1 = np.array([1, -1, 1]).reshape(-1, 1)
v2 = np.array([-1, 1, 0]).reshape(-1, 1)
v3 = np.array([-1, 0, 1]).reshape(-1, 1)

P = np.column_stack([v1, v2, v3])
print(P, "\n")

P_inv = np.linalg.inv(P)
print(P_inv, "\n")

D = np.diag([1, -2, -2])
print(D)

[[ 1 -1 -1]
 [-1  1  0]
 [ 1  0  1]] 

[[ 1.  1.  1.]
 [ 1.  2.  1.]
 [-1. -1. -0.]] 

[[ 1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


In [8]:
P @ D @ P_inv

array([[ 1.,  3.,  3.],
       [-3., -5., -3.],
       [ 3.,  3.,  1.]])

**9.**

In [29]:
A = np.array(
    [
        [3, -1],
        [1, 5]
    ]
)

print(A)

[[ 3 -1]
 [ 1  5]]


In [30]:
np.roots([1, -10, 16])

array([8., 2.])

In [31]:
eig = 2

U, pivots = Matrix(A - eig*np.identity(A.shape[0])).rref()

U = np.array(U).astype(float)

print(U)

[[1. 0.]
 [0. 1.]]


**11.**

In [2]:
A = np.array(
    [
        [-1, 4, -2],
        [-3, 4, 0],
        [-3, 1, 3],
    ]
)

print(A)

[[-1  4 -2]
 [-3  4  0]
 [-3  1  3]]


In [22]:
eigenvalues, eigenvectors = np.linalg.eig(A)

eigenvalues, eigenvectors

(array([1., 2., 3.]),
 array([[-0.57735027,  0.42640143,  0.19611614],
        [-0.57735027,  0.63960215,  0.58834841],
        [-0.57735027,  0.63960215,  0.78446454]]))

In [19]:
eig = 1

U, pivots = Matrix(A - eig*np.identity(3)).rref()

U = np.array(U).astype(float)

basis = U[:, pivots]

basis

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [20]:
eig = 2

U, pivots = Matrix(A - eig*np.identity(3)).rref()

U = np.array(U).astype(float)

basis = U[:, pivots]

basis

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [21]:
eig = 3

U, pivots = Matrix(A - eig*np.identity(3)).rref()

U = np.array(U).astype(float)

basis = U[:, pivots]

basis

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

**32.**

In [5]:
A = np.array(
    [
        [-6, 4, 0, 9],
        [-3, 0, 1, 6],
        [-1, -2, 1, 0],
        [-4, 4, 0, 7]
    ]
)

In [6]:
eigenvalues, eigenvectors = np.linalg.eig(A)

eigenvalues, eigenvectors

(array([ 5.,  1., -2., -2.]),
 array([[-0.63245553,  0.26261287, -0.79971478,  0.32334764],
        [-0.31622777, -0.13130643, -0.30334009, -0.72992629],
        [ 0.31622777, -0.91914503, -0.46879832, -0.37883498],
        [-0.63245553,  0.26261287, -0.22061097,  0.46812175]]))

In [11]:
for eigenvalue in eigenvalues:

    B = A - eigenvalue * np.identity(4)
    basis = scipy.linalg.null_space(B)
    
    print(basis / basis.min())
    print()

[[ 1. ]
 [ 0.5]
 [-0.5]
 [ 1. ]]

[[ 1. ]
 [-0.5]
 [-3.5]
 [ 1. ]]

[[ 1.          0.75088557]
 [-0.68529134  0.88132618]
 [-0.12352756  0.83784598]
 [ 0.74901837 -0.05797361]]

[[-1.12633369  0.35812796]
 [ 0.33660871  1.        ]
 [-0.15103876  0.78604265]
 [-0.65019662 -0.28527646]]

