In [1]:
import numpy as np

**30.**

In [5]:
A = np.array(
    [
        [-14, 4, -14],
        [-33, 9, -31],
        [11, -4, 11],
    ]
)

b1 = np.array([-1, -2, 1]).reshape(-1, 1)
b2 = np.array([-1, -1, 1]).reshape(-1, 1)
b3 = np.array([-1, -2, 0]).reshape(-1, 1)

P = np.column_stack([b1, b2, b3])
P_inv = np.linalg.inv(P)
print(P)
print()
print(P_inv)

[[-1 -1 -1]
 [-2 -1 -2]
 [ 1  1  0]]

[[ 2. -1.  1.]
 [-2.  1. -0.]
 [-1. -0. -1.]]


In [7]:
C = P_inv @ A @ P
print(C)

[[ 8.  3. -6.]
 [ 0.  1.  3.]
 [ 0.  0. -3.]]


**32.**

In [8]:
A = np.array(
    [
        [15, -66, -44, -33],
        [0, 13, 21, -15],
        [1, -15, -21, 12],
        [2, -18, -22, 8],
    ]
)

print(A)

[[ 15 -66 -44 -33]
 [  0  13  21 -15]
 [  1 -15 -21  12]
 [  2 -18 -22   8]]


In [13]:
eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)
print()
print(eigenvectors.round(2))

[2. 5. 4. 4.]

[[-0.   -0.86  0.74 -0.98]
 [-0.64  0.24 -0.35 -0.02]
 [ 0.64 -0.31  0.43 -0.1 ]
 [ 0.43 -0.31  0.39 -0.15]]


In [15]:
P = eigenvectors.copy()
P_inv = np.linalg.inv(P)

D = P_inv @ A @ P

print(D.round(2))

[[ 2. -0.  0.  0.]
 [-0.  5. -0.  0.]
 [-0.  0.  4. -0.]
 [-0. -0. -0.  4.]]
