In [1]:
import numpy as np

**Practice 1.**

In [2]:
A = np.array(
    [
        [7, -2, 0],
        [-2, 6, 2],
        [0, 2, 5],
    ]
)

A = (1/9) * A

print(A)

[[ 0.77777778 -0.22222222  0.        ]
 [-0.22222222  0.66666667  0.22222222]
 [ 0.          0.22222222  0.55555556]]


In [4]:
v1 = np.array([-2, 2, 1]).reshape(-1, 1)
v2 = np.array([2, 1, 2]).reshape(-1, 1)
v3 = np.array([1, 2, -2]).reshape(-1, 1)

P = np.column_stack([v1, v2, v3])

x0 = np.array([1, 11, -2]).reshape(-1, 1)
np.linalg.solve(P, x0)

array([[2.],
       [1.],
       [3.]])

**3.**

In [6]:
p = 0.2

A = np.array(
    [
        [0.5, 0.4],
        [-p, 1.1],
    ]
)

eig_values, eig_vectors = np.linalg.eig(A)

eig_values

array([0.7, 0.9])

**4.**

In [24]:
p = 0.125

A = np.array(
    [
        [0.5, 0.4],
        [-p, 1.1],
    ]
)

eig_values, eig_vectors = np.linalg.eig(A)

print(eig_values)
print(eig_vectors)

[0.6 1. ]
[[-0.9701425  -0.62469505]
 [-0.24253563 -0.78086881]]


In [31]:
eig_vectors[:, 1] / eig_vectors[:, 1].max()

array([1.  , 1.25])

**9.**

In [32]:
A = np.array(
    [
        [1.7, -0.3],
        [-1.2, 0.8],
    ]
)

eig_values, eig_vectors = np.linalg.eig(A)

print(eig_values)
print(eig_vectors)

[2.  0.5]
[[ 0.70710678  0.24253563]
 [-0.70710678  0.9701425 ]]


In [34]:
eig_vectors[:, 1] / eig_vectors[:, 1].min()

array([1., 4.])

**15.**

In [39]:
A = np.array(
    [
        [.4, 0, .2],
        [.3, .8, .3],
        [.3, .2, .5],
    ]
)

x0 = np.array([0, .3, .7]).reshape(-1, 1)

v1 = np.array([0.1, 0.6, 0.3]).reshape(-1, 1)

eigenvalues, P = np.linalg.eig(A)

print(eig_values)
print()
print(P)

[1.  0.2 0.5]

[[ 1.47441956e-01  7.07106781e-01  5.34522484e-01]
 [ 8.84651737e-01  1.35727442e-16 -8.01783726e-01]
 [ 4.42325868e-01 -7.07106781e-01  2.67261242e-01]]


In [37]:
A @ v1

array([[0.1],
       [0.6],
       [0.3]])

In [43]:
c = np.linalg.solve(P, x0)

c

array([[ 0.678233  ],
       [-0.42426407],
       [ 0.37416574]])

NameError: name 'np' is not defined

In [47]:
l = [2, 5, 4, 1]

max_value = 0

for item in l:
    if item > max_value:
        max_value = item

max_value

5