In [1]:
import numpy as np

**43.**

In [2]:
n = 6

In [4]:
A = np.random.uniform(low=-9, high=9, size=(n, n))

print(A.round(2))

[[ 5.78  8.9  -2.43 -8.11 -0.92 -2.17]
 [-0.49  8.86  0.05 -5.89  3.1  -7.28]
 [-1.14 -6.13  7.05  2.07  7.94 -6.71]
 [-1.56 -8.8   4.44  8.96  8.2  -3.46]
 [ 3.16  4.03 -2.13 -7.17  7.55 -6.08]
 [-1.13  7.18  2.    1.98 -1.51  0.96]]


In [5]:
A_inverse = np.linalg.inv(A)

print(A_inverse.round(2))

[[ 0.23 -0.06 -0.01  0.12 -0.08 -0.03]
 [ 0.    0.01 -0.03  0.01  0.03  0.11]
 [ 0.02 -0.11  0.19 -0.13  0.01  0.13]
 [ 0.09  0.08 -0.12  0.19 -0.11 -0.02]
 [-0.12 -0.14  0.02 -0.05  0.23  0.14]
 [-0.14 -0.25  0.07 -0.16  0.23  0.21]]


In [6]:
np.linalg.det(A) * np.linalg.det(A_inverse)

0.9999999999999982

**44.**

In [ ]:
n = 2

A = np.random.rand(n, n)
B = np.random.rand(n, n)

det_A = np.linalg.det(A)
det_B = np.linalg.det(B)

AB = np.dot(A, B)
det_AB = np.linalg.det(AB)

det_AB - det_A * det_B

**45.**

In [ ]:
n = 2

A = np.random.rand(n, n)
B = np.random.rand(n, n)

det_A = np.linalg.det(A)
det_B = np.linalg.det(B)

det_A_B = np.linalg.det(A + B)

det_A_B - (det_A + det_B)

**46.**

In [7]:
n = 5

A = np.random.rand(n, n)

det_A_0 = np.linalg.det(A)

det_A_1 = np.linalg.det(A.transpose())
det_A_2 = np.linalg.det(-A)
det_A_3 = np.linalg.det(10*A)
det_A_4 = np.linalg.det(20*A)

print(det_A_1 / det_A_0)
print(det_A_2 / det_A_0)
print(det_A_3 / det_A_0)
print(det_A_4 / det_A_0)

0.9999999999999982
-1.0
99999.99999999983
3199999.9999999907


In [8]:
print((-1)**n)
print(10**n)
print(20**n)

-1
100000
3200000
