In [1]:
import numpy as np

**45.**

In [7]:
for _ in range(10):

    A = np.random.randint(low=-10, high=10, size=(4, 5))
    A_t = A.transpose()

    print(np.linalg.det(A_t @ A))
    print(np.linalg.det(A @ A_t))
    print()

for _ in range(10):

    A = np.random.randint(low=-10, high=10, size=(5, 6))
    A_t = A.transpose()

    print(np.linalg.det(A_t @ A))
    print(np.linalg.det(A @ A_t))
    print()

-5.696587482979684e-08
11418066.000000011

4.871196018509928e-07
150395410.00000015

-1.8243481779315318e-07
28412604.000000026

-3.0168467633673632e-06
205516043.99999988

2.0311296673463468e-06
564244920.0

-1.4858454850836947e-06
322022780.9999997

-4.088262970949999e-08
23440648.0

5.792578513981135e-09
1108322.0000000175

-1.0354944540102813e-07
28250401.000000082

7.040512082916398e-07
64595557.99999982

1.868787796221408e-06
969958984.0000014

2.6583378941114344e-05
6867882705.000013

-3.2145315984682225e-05
10846276125.000013

-0.0018677468953046147
75078674325.00009

-2.898086475143794e-06
1023523454.999996

4.622156814057842e-05
24355818037.999992

0.00024051793477849787
36978127195.0

-1.3433135397633207e-06
30452402069.999973

-2.4905982365241534e-05
6990590548.999984

2.2026090959292997e-06
1973934480.0000067



**46.**

In [10]:
A = np.array(
    [
        [4, 0, -7, -7],
        [-6, 1, 11, 9],
        [7, -5, 10, 19],
        [-1, 2, 3, -1],
    ]
)

print(A)

[[ 4  0 -7 -7]
 [-6  1 11  9]
 [ 7 -5 10 19]
 [-1  2  3 -1]]


In [21]:
print(np.linalg.det(A))
print(np.linalg.det(10*A))
print(np.linalg.det(0.1*A))

1.000000000000334
9999.999999999813
0.0001000000000000493


In [22]:
print(np.linalg.inv(A))
print(np.linalg.inv(10*A))
print(np.linalg.inv(0.1*A))

[[-1.90000000e+01 -1.40000000e+01  2.15700473e-14  7.00000000e+00]
 [-5.49000000e+02 -4.01000000e+02 -2.00000000e+00  1.96000000e+02]
 [ 2.67000000e+02  1.95000000e+02  1.00000000e+00 -9.50000000e+01]
 [-2.78000000e+02 -2.03000000e+02 -1.00000000e+00  9.90000000e+01]]
[[ -1.9  -1.4   0.    0.7]
 [-54.9 -40.1  -0.2  19.6]
 [ 26.7  19.5   0.1  -9.5]
 [-27.8 -20.3  -0.1   9.9]]
[[-1.90000000e+02 -1.40000000e+02  3.27357189e-13  7.00000000e+01]
 [-5.49000000e+03 -4.01000000e+03 -2.00000000e+01  1.96000000e+03]
 [ 2.67000000e+03  1.95000000e+03  1.00000000e+01 -9.50000000e+02]
 [-2.78000000e+03 -2.03000000e+03 -1.00000000e+01  9.90000000e+02]]


In [15]:
I = np.identity(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
print(np.linalg.det(I))
print(np.linalg.det(10*I))
print(np.linalg.det(0.1*I))

1.0
10000.00000000001
0.00010000000000000009
