In [1]:
import numpy as np

**37.**

In [6]:
A = np.array(
    [
        [6, 2, 9, -6],
        [2, 6, -6, 9],
        [9, -6, 6, 2],
        [-6, 9, 2, 6],
    ]
)

n = 4

print(A)

[[ 6  2  9 -6]
 [ 2  6 -6  9]
 [ 9 -6  6  2]
 [-6  9  2  6]]


In [4]:
eig_values, P = np.linalg.eig(A)

In [5]:
eig_values

array([-11.,  19.,   5.,  11.])

In [8]:
P

array([[ 0.5, -0.5, -0.5,  0.5],
       [-0.5,  0.5, -0.5,  0.5],
       [-0.5, -0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5]])

In [7]:
from scipy.linalg import null_space

lambda_i = eig_values[0]

null_space(A - lambda_i * np.identity(n))

array([[ 0.5],
       [-0.5],
       [-0.5],
       [ 0.5]])

In [12]:
from utils.linalg import orthogonality

P = orthogonality.gram_schmidt(P, normalize=True)

P

array([[ 0.5, -0.5, -0.5,  0.5],
       [-0.5,  0.5, -0.5,  0.5],
       [-0.5, -0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5]])

In [13]:
np.linalg.norm(P[:, [0]])

1.0

In [14]:
D = np.diag(eig_values)

D

array([[-11.,   0.,   0.,   0.],
       [  0.,  19.,   0.,   0.],
       [  0.,   0.,   5.,   0.],
       [  0.,   0.,   0.,  11.]])

In [15]:
P @ D @ P.T

array([[ 6.,  2.,  9., -6.],
       [ 2.,  6., -6.,  9.],
       [ 9., -6.,  6.,  2.],
       [-6.,  9.,  2.,  6.]])