In [19]:
import numpy as np
from scipy.linalg import null_space
import utils

**5.**

In [124]:
A = np.array(
    [
        [4, 11, 14],
        [8, 7, -2],
    ]
)

m, n = A.shape

print(A)

[[ 4 11 14]
 [ 8  7 -2]]


In [135]:
eig_values, V = np.linalg.eig(A.T @ A)

eig_values

array([ 3.60000000e+02, -1.22290504e-14,  9.00000000e+01])

In [132]:
V

array([[-0.33333333, -0.66666667, -0.66666667],
       [-0.66666667,  0.66666667, -0.33333333],
       [-0.66666667, -0.33333333,  0.66666667]])

In [145]:
v = V[:, [2]]

(A.T @ A) @ v / v 

array([[90.],
       [90.],
       [90.]])

In [146]:
eig = eig_values[eig_values > 0]

eig

array([360.,  90.])

In [147]:
sig = np.sqrt(eig)

r = len(sig)
D = np.diag(sig)

print(D)

[[18.97366596  0.        ]
 [ 0.          9.48683298]]


In [148]:
V_r = V[:, eig_values > 0].copy()
V_n_r = null_space(A.T @ A)

print(V_r, "\n")
print(V_n_r)

[[-0.33333333 -0.66666667]
 [-0.66666667 -0.33333333]
 [-0.66666667  0.66666667]] 

[[ 0.66666667]
 [-0.66666667]
 [ 0.33333333]]


In [149]:
Av = (A @ V_r)

U_r = (1/sig) * Av

# U_r = np.where(np.abs(U_r) < 1e-8, 0, U_r)

print(U_r)

[[-0.9486833   0.31622777]
 [-0.31622777 -0.9486833 ]]


In [140]:
Sig = np.zeros(A.shape)
Sig[:r,:r] = D

Sig

array([[18.97366596,  0.        ,  0.        ],
       [ 0.        ,  9.48683298,  0.        ]])

In [150]:
U_r @ Sig @ V[:, [0, 2, 1]].T

array([[ 4., 11., 14.],
       [ 8.,  7., -2.]])