In [1]:
import numpy as np

**32.**

In [72]:
A = np.array(
    [
        [0.5, 0.5, 0.5, 0.5],
        [0.5, 0.5, -0.5, -0.5],
        [0.5, -0.5, 0.5, -0.5],
        [0.5, -0.5, -0.5, 0.5],
    ]
)

print(A)

[[ 0.5  0.5  0.5  0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]


In [10]:
a_1 = A[:, [0]]
a_2 = A[:, [1]]
a_3 = A[:, [2]]
a_4 = A[:, [3]]

print(a_2)

[[ 0.5]
 [ 0.5]
 [-0.5]
 [-0.5]]


In [11]:
for a in A:
    print(np.linalg.norm(a))

1.0
1.0
1.0
1.0


In [5]:
for i, a_i in enumerate(A):
    for j, a_j in enumerate(A):
        print(i+1, j+1, np.dot(a_i, a_j))

1 1 1.0
1 2 0.0
1 3 0.0
1 4 0.0
2 1 0.0
2 2 1.0
2 3 0.0
2 4 0.0
3 1 0.0
3 2 0.0
3 3 1.0
3 4 0.0
4 1 0.0
4 2 0.0
4 3 0.0
4 4 1.0


In [73]:
A.T @ A

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
u = 10 * np.random.rand(4, 1)
v = 10 * np.random.rand(4,1)

print(u)
print(v)

[[8.75182844]
 [7.9130288 ]
 [0.46846318]
 [1.28991896]]
[[8.52953911]
 [9.42014858]
 [4.75001385]
 [0.33589774]]


In [20]:
u_norm = np.linalg.norm(u)
Au_norm = np.linalg.norm(A @ u)

print(u_norm)
print(Au_norm)

11.878294262434576
11.878294262434578


In [21]:
v_norm = np.linalg.norm(v)
Av_norm = np.linalg.norm(A @ v)

print(v_norm)
print(Av_norm)

13.57083989373785
13.570839893737846


In [22]:
(u.T @ v)/(u_norm * v_norm)

array([[0.94200333]])

In [23]:
((A @ u).T @ (A @ v))/(u_norm * v_norm)

array([[0.94200333]])

**33.**

In [31]:
x = np.random.randint(5, size=(4,1))
y = np.random.randint(5, size=(4,1))
v = np.random.randint(5, size=(4,1))

print(x)
print(y)
print(v)

[[2]
 [0]
 [1]
 [0]]
[[1]
 [2]
 [2]
 [4]]
[[2]
 [0]
 [4]
 [3]]


In [32]:
((x.T @ v) / (v.T @ v)) * v

array([[0.55172414],
       [0.        ],
       [1.10344828],
       [0.82758621]])

In [33]:
((y.T @ v) / (v.T @ v)) * v

array([[1.51724138],
       [0.        ],
       [3.03448276],
       [2.27586207]])

In [34]:
(((x + y).T @ v) / (v.T @ v)) * v

array([[2.06896552],
       [0.        ],
       [4.13793103],
       [3.10344828]])

In [35]:
(((10 * x).T @ v) / (v.T @ v)) * v

array([[ 5.51724138],
       [ 0.        ],
       [11.03448276],
       [ 8.27586207]])

In [44]:
x_proj = (((x.T @ v) / (v.T @ v)) * v)

x_proj_scaled = (x_proj / x_proj.max())*4
print(x_proj_scaled)

[[2.]
 [0.]
 [4.]
 [3.]]


In [42]:
print(v)

[[2]
 [0]
 [4]
 [3]]


**34.**

In [45]:
A = np.array(
    [
        [-6, 3, -27, -33, -13],
        [6, -5, 25, 28, 14],
        [8, -6, 34, 38, 18],
        [12, -10, 50, 41, 23],
        [14, -21, 49, 29, 33]
    ]
)

In [65]:
from scipy.linalg import null_space, orth

Row space of A is equal to the column space of A transpose. Orth builds a orthornormal basis.

In [67]:
R = orth(A.T).T

print(R)

[[-0.1697937   0.17333328 -0.6756352  -0.58913655 -0.37089199]
 [ 0.14785201 -0.51743687  0.22182316 -0.70467624  0.40573975]
 [-0.06975271 -0.32402536 -0.67278889  0.33864856  0.56816757]]


Null space of A

In [69]:
N = null_space(A)

In [71]:
R @ N

array([[-1.23526213e-16,  3.23922947e-16],
       [ 1.18190500e-17, -2.10577684e-16],
       [-1.69336501e-15, -3.31169905e-16]])