In [19]:
import numpy as np
from utils.linear_algebra import orthogonality

**10.**

In [8]:
u1 = np.array([3, -3, 0]).reshape(-1, 1)
u2 = np.array([2, 2, -1]).reshape(-1, 1)
u3 = np.array([1, 1, 4]).reshape(-1, 1)

x = np.array([5, -3, 1]).reshape(-1, 1)

U = np.column_stack([u1, u2, u3])

U

array([[ 3,  2,  1],
       [-3,  2,  1],
       [ 0, -1,  4]])

In [3]:
U.T @ U

array([[18,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 18]])

In [12]:
U[:, [1]]

array([[ 2],
       [ 2],
       [-1]])

In [14]:
def proj(x, u):
    return ((x.T @ u) / (u.T @ u)) * u

def decomposition(x, U):
    n = x.shape[0]
    x_d = np.array([])
    for i in range(n):
        u_i = U[:, [i]]
        c_i = ((x.T @ u_i) / (u_i.T @ u_i))
        x_d = np.append(x_d, c_i)
    return x_d.reshape(-1, 1)

decomposition(x, U)

array([[1.33333333],
       [0.33333333],
       [0.33333333]])

**11.**

In [15]:
A = np.array(
    [
        [-6, -3, 6, 1],
        [-1, 2, 1, -6],
        [3, 6, 3, -2],
        [6, -3, 6, -1],
        [2, -1, 2, 3],
        [-3, 6, 3, 2],
        [-2, -1, 2, -3],
        [1, 2, 1, 6],
    ]
)

print(A)

[[-6 -3  6  1]
 [-1  2  1 -6]
 [ 3  6  3 -2]
 [ 6 -3  6 -1]
 [ 2 -1  2  3]
 [-3  6  3  2]
 [-2 -1  2 -3]
 [ 1  2  1  6]]


In [16]:
A.T @ A

array([[100,   0,   0,   0],
       [  0, 100,   0,   0],
       [  0,   0, 100,   0],
       [  0,   0,   0, 100]])

**36.**

In [24]:
U = A / np.linalg.norm(A, axis=0)

print(U)

[[-0.6 -0.3  0.6  0.1]
 [-0.1  0.2  0.1 -0.6]
 [ 0.3  0.6  0.3 -0.2]
 [ 0.6 -0.3  0.6 -0.1]
 [ 0.2 -0.1  0.2  0.3]
 [-0.3  0.6  0.3  0.2]
 [-0.2 -0.1  0.2 -0.3]
 [ 0.1  0.2  0.1  0.6]]


In [28]:
(U.T @ U).round(4)

array([[ 1.,  0., -0.,  0.],
       [ 0.,  1., -0., -0.],
       [-0., -0.,  1., -0.],
       [ 0., -0., -0.,  1.]])

In [29]:
(U @ U.T).round(4)

array([[ 0.82, -0.  , -0.2 ,  0.08,  0.06,  0.2 ,  0.24,  0.  ],
       [-0.  ,  0.42,  0.24,  0.  , -0.2 ,  0.06,  0.2 , -0.32],
       [-0.2 ,  0.24,  0.58,  0.2 , -0.  ,  0.32,  0.  ,  0.06],
       [ 0.08,  0.  ,  0.2 ,  0.82,  0.24, -0.2 ,  0.06, -0.  ],
       [ 0.06, -0.2 , -0.  ,  0.24,  0.18,  0.  , -0.08,  0.2 ],
       [ 0.2 ,  0.06,  0.32, -0.2 ,  0.  ,  0.58, -0.  ,  0.24],
       [ 0.24,  0.2 ,  0.  ,  0.06, -0.08, -0.  ,  0.18, -0.2 ],
       [ 0.  , -0.32,  0.06, -0.  ,  0.2 ,  0.24, -0.2 ,  0.42]])

In [32]:
y = np.random.random((8, 1))

print(y)

[[0.04122542]
 [0.80249837]
 [0.87162486]
 [0.59602295]
 [0.83472744]
 [0.83559956]
 [0.5082649 ]
 [0.25904739]]


In [33]:
p = U @ U.T @ y

p

array([[0.24634884],
       [0.44818758],
       [1.09203623],
       [0.73007239],
       [0.14641858],
       [0.76292947],
       [0.17905516],
       [0.17013432]])

In [37]:
z = y - p

(z.T @ p).round(4)

array([[0.]])