In [1]:
import numpy as np
from utils.linalg import orthogonality

**1.**

In [2]:
u1 = np.array([0, 1, -4, -1]).reshape(-1, 1)
u2 = np.array([3, 5, 1, 1]).reshape(-1, 1)
u3 = np.array([1, 0, 1, -4]).reshape(-1, 1)
u4 = np.array([5, -3, -1, 1]).reshape(-1, 1)

x = np.array([10, -8, 2, 0]).reshape(-1, 1)

In [3]:
v = orthogonality.proj(x, u4)
print(v)

[[10.]
 [-6.]
 [-2.]
 [ 2.]]


In [4]:
w = orthogonality.proj(x, u1) + orthogonality.proj(x, u2) + orthogonality.proj(x, u3)
print(w)

[[ 0.]
 [-2.]
 [ 4.]
 [-2.]]


In [6]:
U = np.column_stack([u1, u2, u3])

orthogonality.proj_W(x, U)

array([[ 0.],
       [-2.],
       [ 4.],
       [-2.]])

**17.**

In [11]:
y = np.array([4, 8, 1]).reshape(-1, 1)

u1 = np.array([2/3, 1/3, 2/3]).reshape(-1, 1)
u2 = np.array([-2/3, 2/3, 1/3]).reshape(-1, 1)

np.linalg.norm(u1)

0.9999999999999999

In [13]:
U = np.column_stack([u1, u2])

print(U)

[[ 0.66666667 -0.66666667]
 [ 0.33333333  0.66666667]
 [ 0.66666667  0.33333333]]


In [14]:
(U.T @ U).round(4)

array([[ 1., -0.],
       [-0.,  1.]])

In [10]:
(U @ U.T).round(4)

array([[ 0.8889, -0.2222,  0.2222],
       [-0.2222,  0.5556,  0.4444],
       [ 0.2222,  0.4444,  0.5556]])

In [15]:
orthogonality.proj_W(y, U)

array([[2.],
       [4.],
       [5.]])

In [16]:
U @ U.T @ y

array([[2.],
       [4.],
       [5.]])