In [1]:
import numpy as np
from utils.linalg import orthogonality

**Practice 1.**

In [2]:
x1 = np.array([1, 1, 1]).reshape(-1, 1)
x2 = np.array([1/3, 1/3, -2/3]).reshape(-1, 1)

In [3]:
v1 = x1.copy()

v2 = x2 - orthogonality.proj(x2, v1)

V = np.column_stack([v1, v2])

V

array([[ 1.        ,  0.33333333],
       [ 1.        ,  0.33333333],
       [ 1.        , -0.66666667]])

In [5]:
U = orthogonality.normalization(V)

U

array([[ 0.57735027,  0.40824829],
       [ 0.57735027,  0.40824829],
       [ 0.57735027, -0.81649658]])

**1.**

In [5]:
x1 = np.array([3, 0, -1]).reshape(-1, 1)
x2 = np.array([8, 5, -6]).reshape(-1, 1)

basis = np.column_stack([x1, x2])

orthogonality.gram_schmidt(basis, normalize=False)

array([[ 3., -1.],
       [ 0.,  5.],
       [-1., -3.]])

**9.**

In [10]:
A = np.array(
    [
        [3, -5, 1],
        [1, 1, 1],
        [-1, 5, -2],
        [3, -7, 8],
    ]
)

print(A)

[[ 3 -5  1]
 [ 1  1  1]
 [-1  5 -2]
 [ 3 -7  8]]


In [11]:
orthogonality.gram_schmidt(A, normalize=False)

array([[ 3.,  1., -3.],
       [ 1.,  3.,  1.],
       [-1.,  3.,  1.],
       [ 3., -1.,  3.]])

**13.**

In [14]:
A = np.array(
    [
        [5, 9],
        [1, 7],
        [-3, -5],
        [1, 5],
    ]
)

Q = np.array(
    [
        [5/6, -1/6],
        [1/6, 5/6],
        [-3/6, 1/6],
        [1/6, 3/6],
    ]
)

print(A, "\n\n", Q)

[[ 5  9]
 [ 1  7]
 [-3 -5]
 [ 1  5]] 

 [[ 0.83333333 -0.16666667]
 [ 0.16666667  0.83333333]
 [-0.5         0.16666667]
 [ 0.16666667  0.5       ]]


In [16]:
R = Q.T @ A

print(R.round(4))

[[ 6. 12.]
 [ 0.  6.]]


In [17]:
Q @ R

array([[ 5.,  9.],
       [ 1.,  7.],
       [-3., -5.],
       [ 1.,  5.]])

**15.**

In [18]:
A = np.array(
    [
        [1, 2, 5],
        [-1, 1, -4],
        [-1, 4, -3],
        [1, -4, 7],
        [1, 2, 1],
    ]
)

print(A)

[[ 1  2  5]
 [-1  1 -4]
 [-1  4 -3]
 [ 1 -4  7]
 [ 1  2  1]]


In [20]:
Q = orthogonality.gram_schmidt(A)
print(Q)

[[ 0.4472136  0.5        0.5      ]
 [-0.4472136  0.         0.       ]
 [-0.4472136  0.5        0.5      ]
 [ 0.4472136 -0.5        0.5      ]
 [ 0.4472136  0.5       -0.5      ]]


In [23]:
R = Q.T @ A
print(R)

[[ 2.23606798 -2.23606798  8.94427191]
 [ 0.          6.         -2.        ]
 [ 0.          0.          4.        ]]


In [24]:
Q @ R

array([[ 1.,  2.,  5.],
       [-1.,  1., -4.],
       [-1.,  4., -3.],
       [ 1., -4.,  7.],
       [ 1.,  2.,  1.]])