In [1]:
import numpy as np
from utils.linalg import matrices

**Practice 1**

In [27]:
A = np.array(
    [
        [1, -3, -3],
        [1, 5, 1],
        [1, 7, 2]
    ]
)

b = np.array([5, -3, -5]).reshape(-1, 1)

In [28]:
A.T @ A

array([[ 3,  9,  0],
       [ 9, 83, 28],
       [ 0, 28, 14]])

In [29]:
rref, pivots = matrices.row_reduction(A.T @ A)

rref

array([[ 1. ,  0. , -1.5],
       [ 0. ,  1. ,  0.5],
       [ 0. ,  0. ,  0. ]])

In [6]:
rref, pivots = matrices.row_reduction_aug(A.T @ A, A.T @ b)

print(rref)

[[ 1.   0.  -1.5  2. ]
 [ 0.   1.   0.5 -1. ]
 [ 0.   0.   0.   0. ]]


**1.**

In [24]:
A = np.array(
    [
        [-1, 2],
        [2, -3],
        [-1, 3],
    ]
)

b = np.array([4, 1, 2]).reshape(-1, 1)

print(A)

[[-1  2]
 [ 2 -3]
 [-1  3]]


In [9]:
A.T @ A

array([[  6, -11],
       [-11,  22]])

In [14]:
np.linalg.det(A.T @ A)

10.999999999999991

In [13]:
A.T @ b

array([[-4],
       [11]])

In [16]:
matrices.row_reduction_aug(A.T @ A, A.T @ b)[0]

array([[1., 0., 3.],
       [0., 1., 2.]])

In [18]:
x_hat = np.array([[3, 2]]).T

A @ x_hat

array([[1],
       [0],
       [3]])

In [25]:
A.T @ b

array([[-4],
       [11]])

In [31]:
42 / 6

7.0

In [33]:
A = np.array([
    [1, -1],
    [0, 0]
])


Q, R = np.linalg.qr(A)

Q

array([[ 1.,  0.],
       [-0.,  1.]])

In [34]:
R

array([[ 1., -1.],
       [ 0.,  0.]])

**13.**

In [35]:
A = np.array(
    [
        [3, 4],
        [-2, 1],
        [3, 4],
    ]
)

b = np.array([11, -9, 5]).reshape(-1, 1) 
u = np.array([5, -1]).reshape(-1, 1) 
v = np.array([5, -2]).reshape(-1, 1) 

In [36]:
A @ u

array([[ 11],
       [-11],
       [ 11]])

In [38]:
A @ v

array([[  7],
       [-12],
       [  7]])