In [27]:
import numpy as np
from scipy.linalg import null_space
from sympy import Matrix

**37.**

In [3]:
A = np.array(
    [
        [7, 6, -4, 1],
        [-5, -1, 0, -2],
        [9, -11, 7, -3],
        [19, -9, 7, 1],
])

w = np.array([1, 1, -1, -3])

In [4]:
A @ w

array([14,  0,  0,  0])

In [17]:
np.linalg.solve(A, w)

array([ 0.00644855, -0.25746799, -0.72176387, -0.38738739])

**39.**

In [23]:
A = np.array(
    [
        [5, 1, 2, 2, 0],
        [3, 3, 2, -1, -12],
        [8, 4, 4, -5, 12],
        [2, 1, 1, 0, -2],
    ]
)

B = A[:, [0, 1, 3]]

In [29]:
Matrix(A).rref()[0]

Matrix([
[1, 0, 1/3, 0,  10/3],
[0, 1, 1/3, 0, -26/3],
[0, 0,   0, 1,    -4],
[0, 0,   0, 0,     0]])

In [28]:
null_space(A)

array([[-0.26555021,  0.40651622],
       [-0.37462332, -0.78470053],
       [ 0.8875449 , -0.22686804],
       [-0.0363577 , -0.39707225],
       [-0.00908943, -0.09926806]])

**40.**

In [55]:
v1 = np.array([5, 3, 8])
v2 = np.array([1, 3, 4])
v3 = np.array([2, -1, 5])
v4 = np.array([0, -12, -28])

A = np.column_stack([v1, v2, -v3, -v4])

A

array([[ 5,  1, -2,  0],
       [ 3,  3,  1, 12],
       [ 8,  4, -5, 28]])

In [52]:
zero = np.zeros(shape=(4, 1))

In [53]:
np.linalg.lstsq(A, zero)

LinAlgError: Incompatible dimensions

In [57]:
A.shape

(3, 4)