In [2]:
import numpy as np
from sympy import Matrix

**36.**

In [11]:
u1 = np.array([1, 2, 0, -1])
u2 = np.array([0, 2, -1, 1])
u3 = np.array([3, 4, 1, -4])

v1 = np.array([-2, -2, -1, 3])
v2 = np.array([2, 3, 2, -6])
v3 = np.array([-1, 4, 6, -2])

A = np.column_stack([u1, u2, u3])
B = np.column_stack([v1, v2, v3])
C = np.concatenate([A, B], axis=1)

In [12]:
print(C)

[[ 1  0  3 -2  2 -1]
 [ 2  2  4 -2  3  4]
 [ 0 -1  1 -1  2  6]
 [-1  1 -4  3 -6 -2]]


In [15]:
Matrix(A).rref()[0]

Matrix([
[1, 0,  3],
[0, 1, -1],
[0, 0,  0],
[0, 0,  0]])

In [16]:
Matrix(B).rref()[0]

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1],
[0, 0, 0]])

In [17]:
Matrix(C).rref()[0]

Matrix([
[1, 0,  3, -2, 0, 0],
[0, 1, -1,  1, 0, 0],
[0, 0,  0,  0, 1, 0],
[0, 0,  0,  0, 0, 1]])