In [4]:
import numpy as np
from sympy import Matrix

In [3]:
A = np.array(
    [
        [7, -9, -4, 5, 3, -3, -7],
        [-4, 6, 7, -2, -6, -5, 5],
        [5, -7, -6, 5, -6, 2, 8],
        [-3, 5, 8, -1, -7, -4, 8],
        [6, -8, -5, 4, 4, 9, 3],
    ]
)

print(A)

[[ 7 -9 -4  5  3 -3 -7]
 [-4  6  7 -2 -6 -5  5]
 [ 5 -7 -6  5 -6  2  8]
 [-3  5  8 -1 -7 -4  8]
 [ 6 -8 -5  4  4  9  3]]


In [5]:
Matrix(A).rref()[0]

Matrix([
[1, 0, 13/2, 0,     5, 0, -3],
[0, 1, 11/2, 0,   1/2, 0,  2],
[0, 0,    0, 1, -11/2, 0,  7],
[0, 0,    0, 0,     0, 1,  1],
[0, 0,    0, 0,     0, 0,  0]])

In [9]:
pivots = Matrix(A).rref()[1]

C = A[:, pivots]

print(C)

[[ 7 -9  5 -3]
 [-4  6 -2 -5]
 [ 5 -7  5  2]
 [-3  5 -1 -4]
 [ 6 -8  4  9]]


In [31]:
Matrix(A).nullspace()[0]

Matrix([
[-13/2],
[-11/2],
[    1],
[    0],
[    0],
[    0],
[    0]])

In [32]:
null_space = Matrix(A).nullspace()

N = np.array(null_space).astype(float).reshape(3, 7).transpose()

print(N)

[[-6.5 -5.   3. ]
 [-5.5 -0.5 -2. ]
 [ 1.   0.   0. ]
 [ 0.   5.5 -7. ]
 [ 0.   1.   0. ]
 [ 0.   0.  -1. ]
 [ 0.   0.   1. ]]


In [42]:
pivots_rows = Matrix(A.T).rref()[1]

U = Matrix(A).rref()[0]

R = np.array(U[pivots_rows, :]).astype(float)

print(R)

[[ 1.   0.   6.5  0.   5.   0.  -3. ]
 [ 0.   1.   5.5  0.   0.5  0.   2. ]
 [ 0.   0.   0.   1.  -5.5  0.   7. ]
 [ 0.   0.   0.   0.   0.   1.   1. ]]
