In [1]:
import numpy as np

**19.**

In [2]:
P = np.array(
    [
        [1, 2, -1],
        [-3, -5, 0],
        [4, 6, 1],
    ]
)

v1 = np.array([-2, 2, 3])
v2 = np.array([-8, 5, 2])
v3 = np.array([-7, 2, 6])

In [5]:
V = np.column_stack([v1, v2, v3])

print(V)

[[-2 -8 -7]
 [ 2  5  2]
 [ 3  2  6]]


In [6]:
V @ P

array([[-6, -6, -5],
       [-5, -9,  0],
       [21, 32,  3]])

**20.**

In [8]:
basis_0 = np.array([
    [7, 5],
    [-3, 1]
]).T

basis_1 = np.array([
    [1, -5],
    [-2, 2]
]).T

basis_2 = np.array([
    [-1, 8],
    [1, -5]
]).T

In [12]:
def change_of_coordinates(base_to, base_from):
    return np.linalg.inv(base_to) @ base_from

P = change_of_coordinates(basis_2, basis_0)
print(P)

P = change_of_coordinates(basis_2, basis_1) @ change_of_coordinates(basis_1, basis_0)
print(P)

[[13.33333333 -4.66666667]
 [20.33333333 -7.66666667]]
[[13.33333333 -4.66666667]
 [20.33333333 -7.66666667]]
