In [15]:
import numpy as np
from sympy import Matrix
from scipy.linalg import null_space

**1.**

In [35]:
P = np.array(
    [
        [0.7, 0.6],
        [0.3, 0.4],
    ]
)

x_0 = np.array([1, 0]).T

P @ (P @ x_0)

array([0.67, 0.33])

In [6]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [10]:
A = np.array(
    [
        [0.1, 0.6],
        [0.9, 0.4],
    ]
)

Matrix(A - np.identity(2)).rref()[0]

Matrix([
[1, -0.666666666666667],
[0,                  0]])

In [7]:
A - np.identity(2)

array([[-0.9,  0.6],
       [ 0.9, -0.6]])

**21.**

In [18]:
A = np.array(
    [
        [.3355, .3682, .3067, .0389],
        [.2663, .2723, .3277, .5451],
        [.1935, .1502, .1589, .2395],
        [.2047, .2093, .2067, .1765],
    ]
)

print(A)

[[0.3355 0.3682 0.3067 0.0389]
 [0.2663 0.2723 0.3277 0.5451]
 [0.1935 0.1502 0.1589 0.2395]
 [0.2047 0.2093 0.2067 0.1765]]


In [14]:
for k in range(2, 5+1):
    P_k = np.linalg.matrix_power(A, k)
    print(P_k.round(4))
    print()

[[0.2779 0.278  0.2803 0.2941]
 [0.3368 0.3355 0.3357 0.3335]
 [0.1847 0.1861 0.1833 0.1697]
 [0.2005 0.2004 0.2007 0.2027]]

[[0.2817 0.2817 0.2817 0.2814]
 [0.3356 0.3356 0.3355 0.3352]
 [0.1817 0.1817 0.1819 0.1825]
 [0.201  0.201  0.201  0.2009]]

[[0.2816 0.2816 0.2816 0.2816]
 [0.3355 0.3355 0.3355 0.3355]
 [0.1819 0.1819 0.1819 0.1819]
 [0.2009 0.2009 0.2009 0.2009]]

[[0.2816 0.2816 0.2816 0.2816]
 [0.3355 0.3355 0.3355 0.3355]
 [0.1819 0.1819 0.1819 0.1819]
 [0.2009 0.2009 0.2009 0.2009]]



In [28]:
v = null_space(A - np.identity(4))

v = v * np.sign(v[0,0]) 

v = v / np.linalg.norm(v)

print(v)

[[0.54672738]
 [0.65130902]
 [0.35316006]
 [0.39008167]]


In [33]:
v = np.linalg.matrix_power(A, 500) @ np.array([1, 0, 1, 0]).T
print(v)

[0.56326538 0.67101051 0.36384282 0.40188128]
